mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from captcha import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('courseselect.urls')),
    url(r'userlogin/', include('userlogin.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url('refresh_captcha/', views.captcha_refresh),    # 刷新验证码，ajax
]

mysite/userlogin/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_login'

urlpatterns = [
    url(r'login', views.login, name='login'),
    # url(r'login_check',views.login_check,name='login_check'),
    url(r'forget_password',views.forget_password,name='forget_password'),
    url(r'find',views.forget_password_do,name='find')
]

mysite/userlogin/models.py
from django.db import models

# class User(models.Model):
#     username=models.CharField(max_length=20)
#     password=models.CharField(max_length=20)
#     mail_address=models.CharField(max_length=20)
#     role=models.IntegerField()
#     name=models.CharField(max_length=20)

mysite/userlogin/forms.py
from django import forms


class UserForm(forms.Form):
    choice = [
        ('teacher', '教师'),
        ('student', '学生'),
    ]
    username = forms.CharField(label='用户名：',max_length=100)
    password = forms.CharField(label='密码：',widget=forms.PasswordInput())
    kind = forms.ChoiceField(label='用户类型', choices=choice)

mysite/userlogin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.http import JsonResponse
from courseselect.models import User, Student, Teacher
from email.mime.text import MIMEText
import smtplib
import json
import random
from .forms import UserForm
from django.shortcuts import get_object_or_404


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            u_id = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            kind = form.cleaned_data['kind']
            request.session['id'] = u_id
            try:
                user = User.objects.get(pk=u_id)
            except:
                return HttpResponse('用户不存在！')
            if user.kind != kind:
                return HttpResponse('请选择正确的用户类型！')
            else:
                if user.password != pwd:
                    return HttpResponse('用户名或密码错误！')
                else:
                    request.session['is_login'] = True
                    if kind == 'student':
                        stu = get_object_or_404(Student, s_id=u_id)
                        context = {'name': stu.name}
                        return render(request, 'student/courseAnnunciate.html', context=context)
                    else:
                        tea = get_object_or_404(Teacher, t_id=u_id)
                        context = {'name': tea.name}
                        return render(request, 'teacher/courseAnnunciate.html', context=context)
    else:
        form = UserForm()
    return render(request, 'index.html', context={'form': form})


def forget_password(request):
    print('进入忘记密码')
    return render(request,'forgetPsw.html') 

verification =""

def forget_password_do(request):
    print('sadsasdasdasdasdasdasdada')
    global verification
    response={}
    api=request.GET.get("api")
    print(api)
    if api=="findInformation":
        try:
            username=request.GET.get("user")
            print(username)
            print(type(username))
            api=request.GET.get("api")
            typeId=request.GET.get("typeId")
            print('获取用户')
        except:
            response["res"]="0"
            print('获取用户失败')
            return JsonResponse(response)

        # 获取数据库数据
        try:
            user=get_object_or_404(User, u_id=username)
            print('用户邮箱：', user.email)
            print(typeId)
            response["res"]="2"
            response["mail_address"]=user.email
        except:
            print('获取用户邮箱失败')
            response["res"]="0"
        return JsonResponse(response)
    elif api=="sendVerification":
        mail_address=request.GET.get("mail_address")
        time=request.GET.get("time")

        verification = ""
        # 生成验证码
        for i in range(6):
            num = random.randrange(0, 4)
            if num == 3 or num == 1:
                rad2 = random.randrange(0, 10)
                verification = verification + str(rad2)
            else:
                rad = random.randrange(65, 91)
                c = chr(rad)
                verification = verification + c
        msg = MIMEText(verification)
        # 设置邮件主题
        msg["Subject"] = "国科大选课密码重置"
        # 寄件者
        msg["From"]= '国科大'
        # 收件者
        msg["To"]= '学生'

        from_addr = "2243829852@qq.com"
        password = "gypadmissdsnebjb"
        # smtp服务器地址
        smtp_server = 'smtp.qq.com'
        # 收件人地址
        to_addr = mail_address

        try:
            # smtp协议的默认端口是25，QQ邮箱smtp服务器端口是465,第一个参数是smtp服务器地址，第二个参数是端口，第三个参数是超时设置,这里必须使用ssl证书，要不链接不上服务器
            server = smtplib.SMTP_SSL(smtp_server, 465, timeout = 2)
            # 登录邮箱
            server.login(from_addr, password)
            #发送邮件，第一个参数是发送方地址，第二个参数是接收方列表，列表中可以有多个接收方地址，表示发送给多个邮箱，msg.as_string()将MIMEText对象转化成文本
            server.sendmail(from_addr, [to_addr], msg.as_string())
            server.quit()
            response["res"]="2"
        except:
            response["res"]="0"
        return JsonResponse(response)
    elif api=="findPassword":
        username=request.GET.get("user")
        typeId=request.GET.get("typeId")
        send_verification=request.GET.get("verification")
        mail_address=request.GET.get("mail_address")
        password=request.GET.get("password")
        print("....................................1")
        print(send_verification)
        print(verification)
        # 为了方便测试，111111为默认可通过的验证码
        if send_verification==verification or send_verification=="111111":
            user=User.objects.get(u_id=username)
            user.password=password
            user.save()
            response["res"]="2"
        else:
            response["res"]="0"
            response["msg"]="验证码错误！"
        return JsonResponse(response)

mysite/userlogin/templates/forgetPsw.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>忘记密码</title>
      <!-- 引入 Bootstrap -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/forgetPsw.css'%}">   
      <link rel="shortcut icon" href="{% static 'img/favicon.ico'%}">
</head>
<body>
  <header><h3>大学生网上选课系统</h3></header>
  <h2>找回密码</h2>
  <div class="progressBar">
    <span class="step active">1</span>
    <span class="line"><span class="gray"></span><span class="green"></span></span>
    <span class="step">2</span>
    <span class="line"><span class="gray"></span><span class="green"></span></span>
    <span class="step">3</span>
    <ul>
      <li>确认账号名</li>
      <li>设置新密码</li>
      <li>设置成功</li>
    </ul>
  </div>
  <div class="container" id="part1">
    <input hidden type="text" id="url" name="url" value="{% url 'user_login:find' %}"></input>
    <p class="form-group" id="userP">
      <label for="user">校园通账号：</label>
      <input type="text" id="user" class="form-control" name="user" data-container="body" data-toggle="popover" data-placement="top" data-content="请正确输入校园通账号" required>
    </p>
    <p class="form-group" id="typeP">
      <label class="checkbox-inline"><input type="radio" name="typeId" value="1" checked>学生</label>
      <label class="checkbox-inline"><input type="radio" name="typeId" value="2">老师</label>
    </p>
    <button type="button" id="submit1" class="btn btn-primary btn-success btn-block submit" name="next">下一步 <span class="glyphicon glyphicon-circle-arrow-right"></span></button>
  </div>
  <div class="container" id="part2">
    <input hidden type="text" id="url" name="url" value="{% url 'user_login:find' %}"></input>
    <label for="tel">邮箱：</label>
    <p class="input-group form-group" id="telP">
      <input type="mail_address" id="mail_address" class="form-control" name="mail_address" readonly>
      <span class="input-group-btn">
        <button class="btn btn-default btn-success" type="button" id="sendCaptcha">发送验证码</button>
      </span>
    </p>
    <p class="form-group" id="verP">
      <label for="verification">验证码：</label>
      <input type="text" id="verification" class="form-control" name="verification" data-container="body" data-toggle="popover" data-placement="top" data-content="请正确输入验证码" required>
    </p>
    <p class="form-group" id="nPswP">
      <label for="newPsw">新密码：</label>
      <input type="password" id="newPsw" class="form-control" name="newPsw" data-container="body" data-toggle="popover" data-placement="top" data-content="密码由6-20个英文、数字组成" required>
    </p>
    <p class="form-group" id="checkP">
      <label for="checkPsw">确认密码：</label>
      <input type="password" id="checkPsw" class="form-control" name="checkPsw" data-container="body" data-toggle="popover" data-placement="top" data-content="与密码不一致" required>
    </p>
     <button type="button" id="submit2" class="btn btn-primary btn-success btn-block submit" name="next">下一步 <span class="glyphicon glyphicon-circle-arrow-right"></span></button>
  </div>
  <div class="container" id="part3">
    <span class="glyphicon glyphicon-ok-sign"></span><span>设置成功！</span><small>现在去 </small><a href="{% url 'user_login:login' %}">登录</a>
  </div>
 <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
  <script src="{% static 'bootstrap/js/jquery-3.1.1.min.js'%}"></script>
  <!-- 包括所有已编译的插件 -->
  <script src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'js/forgetPsw.js'%}"></script>
</body>
</html>

mysite/userlogin/templates/index_stu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>学生主页</title>
</head>
<body>
Welcome, 亲爱的{{ name }}同学！
</body>
</html>

mysite/userlogin/templates/index_tea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>教师主页</title>
</head>
<body>
welcome!{{ name }}老师！
</body>
</html>

mysite/userlogin/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>国科大网上选课系统</title>
      <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static '/css/login.css' %}">   
      <link rel="shortcut icon" href="{% static '/img/favicon.ico' %}">
</head>
<body>
  <h1>大学生网上选课系统</h1>
  <div class="bgImg">
    <img src="{% static '/img/LOGO2.png' %}" alt="logo">
    <div class="loginMain">
    <form action=""> 
      <input hidden type="text" id="url" name="url" value="{% url 'user_login:login' %}"></input>
      <p class="form-group" id="userP">
        <label for="user">校园账号：</label>
        <input type="text" id="user" class="input form-control" name="user" data-container="body" data-toggle="popover" data-placement="top" data-content="请正确输入校园账号" placeholder="学号或教职工号">
      </p>
      <p class="form-group" id="pswP">
        <label for="password">密码</label>：
        <input type="password" id="password" class="input form-control" name="password" data-container="body" data-toggle="popover" data-placement="top" data-content="请正确填写密码">
      </p>
      <a href="{% url 'user_login:forget_password' %}">忘记密码？</a>
      <p class="lastP">
        <label for="type">请选择身份：</label>
        <select name="typeId" class="input form-control" id="typeId">
          <option value="1">学生</option>
          <option value="2">教师</option>
          <option value="0">管理员</option>
        </select>
      </p>
      <input type="checkbox" id="remember" name="remember"> <label for="remember">记住我</label>
    </form>
    <button type="button" id="submit" class="btn btn-primary btn-success btn-block">登录<span class="glyphicon glyphicon-circle-arrow-right"></span></button>
    </div>  
  </div>  
  <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
  <script src="{% static '/bootstrap/js/jquery-3.1.1.min.js' %}"></script>
  <!-- 包括所有已编译的插件 -->
  <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static '/js/login.js' %}"></script></body>
</html>