mysite/courseselect/urls.py
from django.conf.urls import url
from . import views

app_name = 'courseselect'

urlpatterns = [
    url(r'^$', views.login, name='index'),
    url('logout', views.logout, name='logout'),
    url('student/index', views.stu_index, name='stu_index'),
    url('student/courseResult.html', views.selected, name='selected'),
    url('student/courseOnline', views.course_select, name='select'),
    url(r'student/predropxk/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.drop_pre_xk, name='dropprexk'),
    url('student/schdule', views.get_schedule, name='schedule'),
    url('student/grade', views.grade, name='grade'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
    url(r'^student/setnodegree/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.set_no_degree, name='setnodegree'),
    url(r'^student/setdegree/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.set_degree, name='setdegree'),
    url(r'^student/drop/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.drop_course, name='dropcourse'),
    url(r'^student/get/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.get_course, name='getcourse'),
    url(r'student/courseLoved', views.pre_selected, name='preselected'),
    url(r'student/preget/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.get_pre, name='getpre'),
    url(r'student/predrop/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.drop_pre, name='droppre'),
    url(r'student/getcoursepre/(?P<s_id>[0-9]+)/(?P<c_id>\d+)/', views.get_course_pre, name='getcoursepre'),

    url('teacher/downloadFile', views.tea_download_file, name='tea_download_file'),
    url('teacher/courseAnnunciate', views.tea_courseAnnunciate, name='tea_courseAnnunciate'),
    url('teacher/courseResult', views.tea_courseResult, name='tea_courseResult'),
    url('teacher/mySchedule', views.tea_mySchedule, name='tea_mySchedule'),
    url('teacher/courseScore', views.tea_courseScore, name='tea_courseScore'),
    url('teacher/getStuMsg', views.tea_getStuMsg, name='tea_getStuMsg'),
    url('teacher/uploadScore', views.tea_uploadScore, name='tea_uploadScore'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
# from captcha import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'', include('courseselect.urls')),
    url(r'userlogin/', include('userlogin.urls')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url('refresh_captcha/', views.captcha_refresh),    # 刷新验证码，ajax
]

mysite/courseselect/forms.py
from django.forms import ModelForm
from .models import Course
from captcha.fields import CaptchaField
from django import forms


class UserForm(forms.Form):
    choice = [
        ('teacher', '教师'),
        ('student', '学生'),
    ]
    username = forms.CharField(label='用户账号',max_length=100,)
    password = forms.CharField(label='用户密码',widget=forms.PasswordInput())
    kind = forms.ChoiceField(label='用户类型', choices=choice)
    # captcha = CaptchaField(label='验证码', error_messages={'invalid': '验证码错误'})


class SearchForm(forms.Form):
    content = forms.CharField(label='',max_length=20, initial='如：计算机')

mysite/courseselect/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.shortcuts import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import UserForm, SearchForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
import os
import csv
import xlwt
from django.http import JsonResponse
import markdown
import xlrd
from django.http import FileResponse 
from django.views.decorators.csrf import csrf_exempt
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url


# Create your views here.

# def index(request):
#     return redirect('user_login:login')

def login(request):
    if request.session.get('is_login', None):
        if request.session['kind'] == 'student':
            return redirect('courseselect:stu_index')
        else:
            return redirect('courseselect:tea_courseAnnunciate')
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            u_id = form.cleaned_data['username']
            pwd = form.cleaned_data['password']
            kind = form.cleaned_data['kind']
            request.session['id'] = u_id
            request.session['kind'] = kind
            try:
                user = User.objects.get(pk=u_id)
            except:
                response = {}
                response['msg'] = '用户不存在'
                return HttpResponse('用户不存在！')
            if user.kind != kind:
                return HttpResponse('请选择正确的用户类型！')
            else:
                if user.password != pwd:
                    return HttpResponse('用户名或密码错误！')
                else:
                    request.session['is_login'] = True
                    if kind == 'student':
                        stu = get_object_or_404(Student, s_id=u_id)
                        context = {'name': stu.name}
                        return redirect('courseselect:stu_index')
                    else:
                        tea = get_object_or_404(Teacher, t_id=u_id)
                        context = {'name': tea.name}
                        return redirect('courseselect:tea_courseAnnunciate')
    else:
        form = UserForm()
    return render(request, 'courseselect/index.html', context={'form': form})


def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect('courseselect:index')
    request.session.flush()
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect('courseselect:index')


# 学生模块
# 学生主页 主欢迎加边栏功能（选课，已选课程，成绩查询）
def stu_index(request):
    # 先检测登录没有，没有的话就重定向到登陆页面
    if request.session['is_login'] is not True:
        return redirect('courseselect:index')
    else:
        now = timezone.now()
        pk = request.session['id']
        stu = get_object_or_404(Student, s_id=pk)
        posts = Post.objects.all()
        name = stu.name
        s_id = stu.s_id
        time = Date.objects.all()[0]
        if now < time.start_time:
            is_start = 0
        else:
            is_start = 1
        context = {
            'name': name,
            'id': s_id,
            'time': time,
            'is_start': is_start,
            'posts': posts,
        }
        return render(request, 'student/courseAnnunciate.html', context=context)


# 查看已选择的课程
def selected(request):
    if request.session.get('is_login') is None:
        redirect('courseselect:index')
    else:
        pk = request.session['id']
        courses = StudentCourse.objects.filter(student=Student.objects.get(s_id=pk))
        stu = get_object_or_404(Student, s_id=pk)
        total_credit = 0
        degree_credit = 0
        courses_info = []
        for c in courses:
            if c.attribute == 'is':
                degree_credit += c.course.credit
            total_credit += c.course.credit
            course_info = c.course
            courses_info.append([course_info, c.attribute])
        name = stu.name
        s_id = stu.s_id
        context = {
            'courses': courses_info,
            'stu': stu,
            'id': s_id,
            'total_credit': total_credit,
            'degree_credit': degree_credit,
        }
        return render(request, 'student/courseResult.html', context=context)


# 进入选课页面
# 选课页面首先要把所有的课程都列出来，然后选择、提交表单


def course_select(request):
    if request.method == "POST":
        s_form = SearchForm(request.POST)
        if s_form.is_valid():
            content = s_form.cleaned_data['content']
            courses = Course.objects.filter(name__contains=content)
    else:
        courses = Course.objects.all()
    if request.session.get('is_login', None) is None:
        return redirect('courseselect:index')
    pk = request.session['id']
    form = SearchForm()
    stu = get_object_or_404(Student, s_id=pk)
    selected_courses = StudentCourse.objects.filter(student=Student.objects.get(s_id=pk))
    loved = []
    for sc in selected_courses:
        if sc.course in courses:
            courses = courses.exclude(c_id=sc.course.c_id)
    courses = sorted(courses, key=lambda course: course.hot_value, reverse=True)

    paginator1 = Paginator(courses, 2)
    page = request.GET.get('page')
    courses = paginator1.get_page(page)
    for c in courses:
        try:
            Pre.objects.get(student=Student.objects.get(s_id=pk), course=c)
            loved.append('1')
        except:
            loved.append('0')
    loved = zip(courses, loved)
    context = {'courses': courses, 'stu': stu, 'selected_courses': selected_courses, 'form': form,'loved': loved }
    return render(request, 'student/courseOnline.html', context=context)


# 成绩查询
def grade(request):
    stu = get_object_or_404(Student, s_id=request.session['id'])
    scs = StudentCourse.objects.filter(student=Student.objects.get(s_id=request.session['id']))
    context = {
        'stu': stu,
        'scs': scs,
    }
    return render(request, 'student/courseAch.html', context=context)


# 查看课表并下载
def get_schedule(request):
    if request.session.get('is_login') is not True:
        redirect('courseselect:index')
    stu = get_object_or_404(Student, s_id=request.session['id'])
    scs = StudentCourse.objects.filter(student=stu)
    courses = []
    for sc in scs:
        courses.append(sc.course)
    context = {
        'name': stu.name,
        'courses': courses,
    }
    courses = sorted(courses, key=lambda course: course.weekdays)
    return render(request, 'student/mySchedule.html', context=context)


# 设为非学位课
def set_no_degree(request, s_id, c_id):
    c = StudentCourse.objects.get(student=Student.objects.get(s_id=s_id), course=Course.objects.get(c_id=c_id))
    c.attribute = 'not'
    c.save()
    return redirect(reverse('courseselect:selected'))


# 设为非学位课
def set_degree(request, s_id, c_id):
    c = StudentCourse.objects.get(student=Student.objects.get(s_id=s_id), course=Course.objects.get(c_id=c_id))
    c.attribute = 'is'
    c.save()
    return redirect(reverse('courseselect:selected'))


# 退选
def drop_course(request, s_id, c_id):
    c = StudentCourse.objects.get(student=Student.objects.get(s_id=s_id), course=Course.objects.get(c_id=c_id))
    course = Course.objects.get(c_id=c_id)
    c.delete()
    course.selected_now -= 1
    course.save()
    return redirect(reverse('courseselect:selected'))


# 判断是否选课冲突
def allow(course, courses):
    sw = course.start_week
    ew = course.end_week
    wd = course.weekdays
    st = course.start_time
    et = course.end_time
    for c in courses:
        if c.start_week < ew or c.end_week > sw:
            if wd == c.weekdays:
                if c.start_time <  st and c.end_time < st:
                    return True, None
                elif c.start_time > et:
                        return True, None
                else:
                    return False, c
    return True, None


# 判断人数是否满了
def is_full(c_id):
    course = get_object_or_404(Course, c_id=c_id)
    if course.selected_now + 1 <= course.selected_limit:
        return False
    return True


# 选课按钮
def get_course(request, s_id, c_id):
    now = timezone.now()
    date = Date.objects.all()[0]
    if now < date.start_time:
        return HttpResponse("选课尚未开始")
    if now > date.end_time:
        return HttpResponse("选课已经结束")
    full = is_full(c_id)
    courses = []
    aim_course = get_object_or_404(Course, c_id=c_id)
    scs = StudentCourse.objects.filter(student=Student.objects.get(s_id=s_id))
    for sc in scs:
        courses.append(sc.course)
    tag, conflict = allow(aim_course, courses)
    if tag and not full:
        c = StudentCourse(student=Student.objects.get(s_id=s_id), course=Course.objects.get(c_id=c_id))
        c.save()
        aim_course.selected_now += 1
        aim_course.save()
        return redirect(reverse('courseselect:select'))
    elif not tag and not full:
        return HttpResponse("与" + conflict.name + '冲突')
    else:
        return HttpResponse("选课人数已满")


# 正式选课页面取消收藏
def drop_pre_xk(request, s_id, c_id):
    co = Course.objects.get(c_id=c_id)
    cs = Pre.objects.filter(student=Student.objects.get(s_id=s_id), course=co)
    for c in cs:
        c.delete()
    co.hot_value -= 1
    co.save()
    return redirect(reverse('courseselect:select'))


# 预选课界面
def pre_selected(request):
    if request.session.get('is_login') is None:
        redirect('courseselect:index')
    s_id = request.session['id']
    stu = get_object_or_404(Student, s_id=s_id)
    scs = Pre.objects.filter(student=Student.objects.get(s_id=s_id))
    courses = []
    for sc in scs:

mysite/courseselect/templates/teacher/courseAnnunciate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>教师课程管理系统</title>
      <!-- 引入 Bootstrap -->
      <link href="{% static '/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet"> 
      <link rel="stylesheet" href="{% static '/css/courseSystem.css'%}">
      <link rel="stylesheet" href="{% static '/css/courseAunnciate.css' %}">
      <link rel="shortcut icon" href="{% static '/img/favicon.ico'%}">
</head>
<body>

  <div class="navigation">
    <ul>
      <li><a class="active" href="{% url 'courseselect:tea_courseAnnunciate' %}"><span class="navIcon" id="annunciate"></span><p>选课公告</p></a></li>
      <li><a href="{% url 'courseselect:tea_courseResult' %}"><span class="navIcon" id="result"></span><p>选课结果</p></a></li> 
      <li><a href="{% url 'courseselect:tea_courseScore' %}"><span class="navIcon" id="schedule"></span><p>成绩录入</p></a></li>
      <li><a href="{% url 'courseselect:tea_mySchedule' %}"><span class="navIcon" id="schedule"></span><p>我的课表</p></a></li>
    </ul>
  </div>
  <div class="contain">
    <header><h3>国科大网上选课系统</h3><span>欢迎：{{ name }}！ <a href="{% url 'courseselect:logout' %}"
                                                      class="safeExit">退出</a></span></header>
    <div class="main">
        <ul class="nav nav-tabs nav-justified" id="headNav">
            <li data="openCourse" class="active"><a data-toggle="tab" href="#part1">公告</a></li>

        </ul>

        <div class="white">
            <div class="tab-content">
                <div id="part1" class="tab-pane fade in active">
                    <div class="timeDiv">
                        <p>
                            {% if is_start == 0 %}
                            <b>开始时间：</b>
                            <span class="orangeTime">{{ time.start_time|date:"Y-m-d H:i:s" }}</span>
                            {% else %}
                            <b>结束时间：</b>
                            <span class="orangeTime">{{ time.end_time|date:"Y-m-d H:i:s" }}</span>
                            {% endif %}
                    </div>
                    <div class="panel-group" id="accordion1">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion1"
                                       href="#collapseOne">
                                        <span class="glyphicon glyphicon-hand-right"></span> 选课公告
                                    </a>
                                </h4>
                            </div>
                           <div id="collapseOne" class="panel-collapse collapse in" >
                                <div class="panel-body" style="text-align:left;">
                                    <div class="annouceImg" id="annouce1" >
                                        <!-- <iframe id="" name="" src="../file/open.html" frameborder="0"></iframe> -->

                                        {% for post in posts %}
                                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a><hr />
                                        {% endfor %}
                                        <iframe src="" frameborder="0" scrolling="auto" name="main" id="printID"
                                                style=" VISIBILITY: inherit;  Z-INDEX: 1;">
                                        </iframe>
                                    </div>
                                    <!--                    <button class="btn btn-info print">打印</button>-->
                                </div>
                            </div>
                        </div>
                    </div><!-- panel-group 结束-->
                </div><!-- part1 结束 -->
            </div><!-- white 结束 -->
        </div><!-- main 结束 -->
    </div><!-- contain 结束 -->
    <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
    <script src="{% static 'bootstrap/js/jquery-3.1.1.min.js' %}"></script>
    <!-- 包括所有已编译的插件 -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cookies.js' %}"></script>
    <script src="{% static 'js/courseAunnciate.js' %}"></script>
</body>
</html>

mysite/courseselect/templates/teacher/courseResult.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>大学生网上选课系统</title>
      <!-- 引入 Bootstrap -->
      <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static '/css/courseSystem.css'%}">
      <link rel="stylesheet" href="{% static '/css/courseDelete.css'%}">
      <link rel="shortcut icon" href="{% static '/img/favicon.ico'%}">
      <script src="{% static '/js/template-native.js'%}"></script>
</head>
<body>

  <div class="navigation">
    <ul>
      <li><a href="{% url 'courseselect:tea_courseAnnunciate' %}"><span class="navIcon" id="annunciate"></span><p>选课公告</p></a></li>
      <li><a class="active" href="{% url 'courseselect:tea_courseResult' %}"><span class="navIcon" id="result"></span><p>选课结果</p></a></li> 
      <li><a href="{% url 'courseselect:tea_courseScore' %}"><span class="navIcon" id="schedule"></span><p>成绩录入</p></a></li>
      <li><a href="{% url 'courseselect:tea_mySchedule' %}"><span class="navIcon" id="schedule"></span><p>我的课表</p></a></li>
    </ul>
  </div>
  <div class="contain">
    <header><h3>大学生网上选课系统</h3><span><label></label>｜<a href="course_select" class="safeExit">安全退出</a></span></header>
    <div class="main"> 
      <div class="white">
      <div class="tab-content">
        <div id="part1" class="tab-pane fade in active">
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#accordion" 
                     href="#collapseOne">
                    <span class="glyphicon glyphicon-hand-right"></span> 有效已选课程
                  </a>
                </h4>
              </div>
              <div id="collapseOne" class="panel-collapse collapse in">
                <div class="panel-body">
                <div id="openValidTable">
                  
                </div>

                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                          {% comment %} <th>&nbsp;</th> {% endcomment %}
                          <th>课程号</th>
                          <th>课程名</th>
                          <th>学分</th>
                          <th>上课地点</th>
                          <th>上课周数</th>
                          <th>上课节数</th>
                          <th>星期</th>
                          <th>已选人数</th>
                          <th>可选人数</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for course in list %}
                        <tr id="{{ course.id }}">
                          {% comment %} <td><input type="checkbox" name="openCourse" value="{{course.id}}"></td> {% endcomment %}
                          <td>{{course.course_no}}</td>
                          <td>{{course.subject_name }}</td>
                          <td>{{course.credit }}</td> 
                          <td>{{course.place }}</td>
                          <td>{{course.start_week }}～{{course.end_week}}周</td>
                          <td>{{course.course_section }}节</td>
                          <td>{{course.course_weekday }}</td>
                          <td onclick="goList({{course.id }},'{{course.subject_name }}');">
                          <a href="{% url 'courseselect:tea_getStuMsg' %}?course_no={{course.course_no}}">{{course.check_people }}</a></td>
                          <td>{{course.people_max }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div> 
                </div><!-- panel-body 结束 -->
              </div>
            </div><!-- panel 结束 -->
          </div><!-- panel-group 结束-->
        </div><!-- part3 结束 --> 

      </div><!-- tab-content 结束 -->
      </div><!-- white 结束 -->
    </div><!-- main 结束 -->
  </div><!-- contain 结束 -->
   <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
   <script src="{% static '/bootstrap/js/jquery-3.1.1.min.js'%"></script>
   <!-- 包括所有已编译的插件 -->
   <script src="{% static '/bootstrap/js/bootstrap.min.js' %}"></script>
   <script src="{% static '/js/cookies.js' %}"></script>
   <script src="{% static '/js/teacher_courseResult.js'%}"></script>
</body>
</html>

mysite/courseselect/templates/teacher/courseScore.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>教师课程管理系统</title>
      <!-- 引入 Bootstrap -->
      <link href="{% static '/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="{% static '/css/courseSystem.css'%}">
      <link rel="stylesheet" href="{% static '/css/courseDelete.css'%}">
      <link rel="shortcut icon" href="{% static '/img/favicon.ico'%}">
      <script src="{% static '/js/template-native.js'%}"></script>
</head>

<body>

  <div class="navigation">
    <ul>
      <li><a href="{% url 'courseselect:tea_courseAnnunciate' %}"><span class="navIcon" id="annunciate"></span><p>选课公告</p></a></li>
      <li><a href="{% url 'courseselect:tea_courseResult' %}"><span class="navIcon" id="result"></span><p>选课结果</p></a></li> 
      <li><a class="active" href="{% url 'courseselect:tea_courseScore' %}"><span class="navIcon" id="schedule"></span><p>成绩录入</p></a></li>
      <li><a href="{% url 'courseselect:tea_mySchedule' %}"><span class="navIcon" id="schedule"></span><p>我的课表</p></a></li>
    </ul>
  </div>

  <div class="contain">
    <header><h3>教师课程管理系统</h3><span><label></label>｜<a href="{% url 'courseselect:logout' %}" class="safeExit">安全退出</a></span></header>
    <div class="main">
      <div class="white">
        <div class="tab-content">
          <div id="part1" class="tab-pane fade in active">
            <div class="panel-group" id="accordion">
              {% for course in course_all %}
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title">
                      <a data-toggle="collapse" data-parent="#accordion" 
                        href="#{{course.course_no}}">
                        <span class="glyphicon glyphicon-hand-right"></span>{{course.course_name}}
                      </a>
                    </h4>
                  </div>
                  <div id="{{course.course_no}}" class="panel-collapse collapse ">
                    <div class="panel-body"> 
                      <form action="">
                        <div class="table-responsive">
                          <table class="table table-striped table-bordered table-hover">
                            
                            <thead>
                              <tr>
                                <th>姓名</th>
                                <th>学号</th>
                                <th>学院</th>
                                <th>分数</th> 
                              </tr>
                            </thead>

                            <tbody> 
                              {% for stu in course.students %} 
                                <tr>
                                  <td id="stu_name" name="stu_name">{{stu.stu_name}}</td>
                                  <td>
                                    <input hidden value="{{stu.stu_no}}" id="stu_no" name="stu_no">{{stu.stu_no}}</input>
                                  </td>
                                  <td>{{stu.stu_academy}}</td> 
                                  <td>{{stu.grade}}</td> 
                                </tr>
                              {% endfor %}
                            </tbody>

                          </table>
                        </div><!-- table-responsive结束 --> 
                      </form> 
                      <a class="btn btn-success"  href="{% url 'courseselect:tea_download_file' %}?course_no={{course.course_no}}">下载模板</a>
                     
                    
                    <br/>

                    <form enctype="multipart/form-data" action="{% url 'courseselect:tea_uploadScore' %}" method="post">

                        {% csrf_token %}
                        <input  type="file" id="{{course.course_no}}stu_score" name="stu_score" accept=".xls"/>
                        <input  hidden type="text" id="{{course.course_no}}course_no" name="course_no" value="{{course.course_no}}"/>
                        <input  hidden type="text" id="url" name="url" value="{% url 'courseselect:tea_uploadScore' %}"/>
                        <button type="button" id="{{course.course_no}}" value="111">上传成绩</button>
                    </form>

                    </div><!-- panel-body 结束 -->
                  </div>
                </div><!-- panel 结束 -->
              {% endfor %}
            </div><!-- panel-group结束 -->
          </div><!-- part1 结束 --> 
        </div><!-- tab-content结束 -->
      </div><!-- white 结束 -->
    </div><!-- main 结束 -->
  </div><!-- contain 结束 -->
   <!-- jQuery (Bootstrap 的 JavaScript 插件需要引入 jQuery) -->
   <script src="{% static '/bootstrap/js/jquery-3.1.1.min.js'%}"></script>
   <!-- 包括所有已编译的插件 -->
   <script src="{% static '/bootstrap/js/bootstrap.min.js'%}"></script> 
   <script src="{% static '/js/teacher_courseScore.js'%}"></script>
</body>
</html>